name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    strategy:
      matrix:
        python_version: ['3.6.x', '3.7.x']
        pg_version: ['10', '11']
        django_version: ['2.1.15', '2.2.16']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: ${{ matrix.pg_version }}
        postgresql db: smartmin
        postgresql user: smartmin
        postgresql password: nyaruka

    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}

    - name: Initialize environment
      run: |
        pip install -q -r requirements/base.txt
        pip install -q -r requirements/tests.txt
        pip install -q django==${{ matrix.django_version }}
        pip install codecov

    - name: Run tests
      run: |
        coverage run manage.py test --keepdb --noinput --verbosity=2
        coverage report -i

    - name: Upload coverage
      if: success()
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
